 (cd "$(git rev-parse --show-toplevel)" && git apply --3way <<'EOF' 
diff --git a//dev/null b/mobile/pubspec.yaml
index 0000000000000000000000000000000000000000..f4f2c8805d5e80a48028f12b450bfb17fba0354b 100644
--- a//dev/null
+++ b/mobile/pubspec.yaml
@@ -0,0 +1,21 @@
+name: clothing_brand_mobile
+description: Mobile app for clothing brand using Supabase.
+publish_to: 'none'
+version: 1.0.0+1
+
+environment:
+  sdk: '>=3.0.0 <4.0.0'
+
+dependencies:
+  flutter:
+    sdk: flutter
+  supabase_flutter: ^2.0.0
+  cupertino_icons: ^1.0.2
+
+dev_dependencies:
+  flutter_test:
+    sdk: flutter
+  flutter_lints: ^2.0.0
+
+flutter:
+  uses-material-design: true
 
EOF
)
